using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blog.Entity;
using Microsoft.EntityFrameworkCore;

namespace Blog.Data.Concrete.EfCore
{
    public class BlogContext : DbContext
    {
        public BlogContext(DbContextOptions options):base(options)
        {
            
        }
        public DbSet<Article> Articles { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<ArticleCategory> ArticleCategories { get; set; }
        public DbSet<Comment> Comments { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        { 
            modelBuilder
                .Entity<ArticleCategory>()
                .HasKey(ac=>new{
                    ac.ArticleId,
                    ac.CategoryId
                });
            modelBuilder
                .Entity<Article>()
                .HasData(
                    new Article() { ArticleId = 1, Title = "lectus proin nibh nisl condimentum", Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consequat mauris nunc congue nisi vitae. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Sed arcu non odio euismod lacinia at quis risus. Eget nunc lobortis mattis aliquam. In hac habitasse platea dictumst quisque sagittis. Turpis tincidunt id aliquet risus feugiat in ante metus. Varius vel pharetra vel turpis nunc eget. Quam vulputate dignissim suspendisse in est ante. Orci phasellus egestas tellus rutrum tellus. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Sapien eget mi proin sed libero enim sed. Aliquam eleifend mi in nulla. Tellus cras adipiscing enim eu turpis. Varius morbi enim nunc faucibus a pellentesque sit. Ipsum consequat nisl vel pretium lectus quam. Magnis dis parturient montes nascetur. Amet nisl suscipit adipiscing bibendum est ultricies integer quis. Tincidunt dui ut ornare lectus sit amet est placerat in Aliquam etiam erat velit scelerisque in dictum non consectetur a.Pharetra magna ac placerat vestibulum lectus mauris.Gravida arcu ac tortor dignissim convallis aenean.Placerat vestibulum lectus mauris ultrices eros in cursus turpis.Fames ac turpis egestas integer eget aliquet nibh praesent.Turpis cursus in hac habitasse platea dictumst quisque.Porttitor eget dolor morbi non arcu.Diam sollicitudin tempor id eu nisl.Quam nulla porttitor massa id.Cras sed felis eget velit.Suspendisse in est ante in nibh.Sapien faucibus et molestie ac feugiat sed lectus vestibulum.Sit amet cursus sit amet dictum sit amet justo donec.Purus sit amet luctus venenatis lectus magna fringilla urna porttitor.Dictum fusce ut placerat orci nulla.Felis eget nunc lobortis mattis.Lacus luctus accumsan tortor posuere.In nibh mauris cursus mattis.Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a.Aliquet risus feugiat in ante metus dictum.Sagittis nisl rhoncus mattis rhoncus urna.Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras.Nunc id cursus metus aliquam.Gravida cum sociis natoque penatibus et magnis dis parturient.Velit laoreet id donec ultrices tincidunt arcu non sodales neque.Malesuada fames ac turpis egestas sed tempus urna et.Porttitor leo a diam sollicitudin tempor id eu nisl nunc.Non sodales neque sodales ut.Morbi enim nunc faucibus a pellentesque sit.Hac habitasse platea dictumst vestibulum rhoncus est pellentesque.In est ante in nibh mauris cursus.", CreateDate = "2022-10-17 12:56:30", ViewsCount = 15, Score = 4.1, IsApproved = true, ImageUrl = "1.jpg"},
                    new Article() { ArticleId = 2, Title = "lectus proin nibh nisl condimentum", Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consequat mauris nunc congue nisi vitae. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Sed arcu non odio euismod lacinia at quis risus. Eget nunc lobortis mattis aliquam. In hac habitasse platea dictumst quisque sagittis. Turpis tincidunt id aliquet risus feugiat in ante metus. Varius vel pharetra vel turpis nunc eget. Quam vulputate dignissim suspendisse in est ante. Orci phasellus egestas tellus rutrum tellus. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Sapien eget mi proin sed libero enim sed. Aliquam eleifend mi in nulla. Tellus cras adipiscing enim eu turpis. Varius morbi enim nunc faucibus a pellentesque sit. Ipsum consequat nisl vel pretium lectus quam. Magnis dis parturient montes nascetur. Amet nisl suscipit adipiscing bibendum est ultricies integer quis. Tincidunt dui ut ornare lectus sit amet est placerat in Aliquam etiam erat velit scelerisque in dictum non consectetur a.Pharetra magna ac placerat vestibulum lectus mauris.Gravida arcu ac tortor dignissim convallis aenean.Placerat vestibulum lectus mauris ultrices eros in cursus turpis.Fames ac turpis egestas integer eget aliquet nibh praesent.Turpis cursus in hac habitasse platea dictumst quisque.Porttitor eget dolor morbi non arcu.Diam sollicitudin tempor id eu nisl.Quam nulla porttitor massa id.Cras sed felis eget velit.Suspendisse in est ante in nibh.Sapien faucibus et molestie ac feugiat sed lectus vestibulum.Sit amet cursus sit amet dictum sit amet justo donec.Purus sit amet luctus venenatis lectus magna fringilla urna porttitor.Dictum fusce ut placerat orci nulla.Felis eget nunc lobortis mattis.Lacus luctus accumsan tortor posuere.In nibh mauris cursus mattis.Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a.Aliquet risus feugiat in ante metus dictum.Sagittis nisl rhoncus mattis rhoncus urna.Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras.Nunc id cursus metus aliquam.Gravida cum sociis natoque penatibus et magnis dis parturient.Velit laoreet id donec ultrices tincidunt arcu non sodales neque.Malesuada fames ac turpis egestas sed tempus urna et.Porttitor leo a diam sollicitudin tempor id eu nisl nunc.Non sodales neque sodales ut.Morbi enim nunc faucibus a pellentesque sit.Hac habitasse platea dictumst vestibulum rhoncus est pellentesque.In est ante in nibh mauris cursus.", CreateDate = "2022-10-17 12:56:30", ViewsCount = 18, Score = 3.1, IsApproved = true, ImageUrl = "2.jpg"},
                    new Article() { ArticleId = 3, Title = "lectus proin nibh nisl condimentum", Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consequat mauris nunc congue nisi vitae. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Sed arcu non odio euismod lacinia at quis risus. Eget nunc lobortis mattis aliquam. In hac habitasse platea dictumst quisque sagittis. Turpis tincidunt id aliquet risus feugiat in ante metus. Varius vel pharetra vel turpis nunc eget. Quam vulputate dignissim suspendisse in est ante. Orci phasellus egestas tellus rutrum tellus. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Sapien eget mi proin sed libero enim sed. Aliquam eleifend mi in nulla. Tellus cras adipiscing enim eu turpis. Varius morbi enim nunc faucibus a pellentesque sit. Ipsum consequat nisl vel pretium lectus quam. Magnis dis parturient montes nascetur. Amet nisl suscipit adipiscing bibendum est ultricies integer quis. Tincidunt dui ut ornare lectus sit amet est placerat in Aliquam etiam erat velit scelerisque in dictum non consectetur a.Pharetra magna ac placerat vestibulum lectus mauris.Gravida arcu ac tortor dignissim convallis aenean.Placerat vestibulum lectus mauris ultrices eros in cursus turpis.Fames ac turpis egestas integer eget aliquet nibh praesent.Turpis cursus in hac habitasse platea dictumst quisque.Porttitor eget dolor morbi non arcu.Diam sollicitudin tempor id eu nisl.Quam nulla porttitor massa id.Cras sed felis eget velit.Suspendisse in est ante in nibh.Sapien faucibus et molestie ac feugiat sed lectus vestibulum.Sit amet cursus sit amet dictum sit amet justo donec.Purus sit amet luctus venenatis lectus magna fringilla urna porttitor.Dictum fusce ut placerat orci nulla.Felis eget nunc lobortis mattis.Lacus luctus accumsan tortor posuere.In nibh mauris cursus mattis.Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a.Aliquet risus feugiat in ante metus dictum.Sagittis nisl rhoncus mattis rhoncus urna.Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras.Nunc id cursus metus aliquam.Gravida cum sociis natoque penatibus et magnis dis parturient.Velit laoreet id donec ultrices tincidunt arcu non sodales neque.Malesuada fames ac turpis egestas sed tempus urna et.Porttitor leo a diam sollicitudin tempor id eu nisl nunc.Non sodales neque sodales ut.Morbi enim nunc faucibus a pellentesque sit.Hac habitasse platea dictumst vestibulum rhoncus est pellentesque.In est ante in nibh mauris cursus.", CreateDate = "2022-11-17 10:56:30", ViewsCount = 25, Score = 4.5, IsApproved = true, ImageUrl = "3.jpg" },
                    new Article() { ArticleId = 4, Title = "lectus proin nibh nisl condimentum", Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consequat mauris nunc congue nisi vitae. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Sed arcu non odio euismod lacinia at quis risus. Eget nunc lobortis mattis aliquam. In hac habitasse platea dictumst quisque sagittis. Turpis tincidunt id aliquet risus feugiat in ante metus. Varius vel pharetra vel turpis nunc eget. Quam vulputate dignissim suspendisse in est ante. Orci phasellus egestas tellus rutrum tellus. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Sapien eget mi proin sed libero enim sed. Aliquam eleifend mi in nulla. Tellus cras adipiscing enim eu turpis. Varius morbi enim nunc faucibus a pellentesque sit. Ipsum consequat nisl vel pretium lectus quam. Magnis dis parturient montes nascetur. Amet nisl suscipit adipiscing bibendum est ultricies integer quis. Tincidunt dui ut ornare lectus sit amet est placerat in Aliquam etiam erat velit scelerisque in dictum non consectetur a.Pharetra magna ac placerat vestibulum lectus mauris.Gravida arcu ac tortor dignissim convallis aenean.Placerat vestibulum lectus mauris ultrices eros in cursus turpis.Fames ac turpis egestas integer eget aliquet nibh praesent.Turpis cursus in hac habitasse platea dictumst quisque.Porttitor eget dolor morbi non arcu.Diam sollicitudin tempor id eu nisl.Quam nulla porttitor massa id.Cras sed felis eget velit.Suspendisse in est ante in nibh.Sapien faucibus et molestie ac feugiat sed lectus vestibulum.Sit amet cursus sit amet dictum sit amet justo donec.Purus sit amet luctus venenatis lectus magna fringilla urna porttitor.Dictum fusce ut placerat orci nulla.Felis eget nunc lobortis mattis.Lacus luctus accumsan tortor posuere.In nibh mauris cursus mattis.Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a.Aliquet risus feugiat in ante metus dictum.Sagittis nisl rhoncus mattis rhoncus urna.Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras.Nunc id cursus metus aliquam.Gravida cum sociis natoque penatibus et magnis dis parturient.Velit laoreet id donec ultrices tincidunt arcu non sodales neque.Malesuada fames ac turpis egestas sed tempus urna et.Porttitor leo a diam sollicitudin tempor id eu nisl nunc.Non sodales neque sodales ut.Morbi enim nunc faucibus a pellentesque sit.Hac habitasse platea dictumst vestibulum rhoncus est pellentesque.In est ante in nibh mauris cursus.", CreateDate = "2022-10-17 11:56:30", ViewsCount = 75, Score = 2.1, IsApproved = true, ImageUrl = "4.jpg" },
                    new Article() { ArticleId = 5, Title = "lectus proin nibh nisl condimentum", Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consequat mauris nunc congue nisi vitae. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Sed arcu non odio euismod lacinia at quis risus. Eget nunc lobortis mattis aliquam. In hac habitasse platea dictumst quisque sagittis. Turpis tincidunt id aliquet risus feugiat in ante metus. Varius vel pharetra vel turpis nunc eget. Quam vulputate dignissim suspendisse in est ante. Orci phasellus egestas tellus rutrum tellus. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Sapien eget mi proin sed libero enim sed. Aliquam eleifend mi in nulla. Tellus cras adipiscing enim eu turpis. Varius morbi enim nunc faucibus a pellentesque sit. Ipsum consequat nisl vel pretium lectus quam. Magnis dis parturient montes nascetur. Amet nisl suscipit adipiscing bibendum est ultricies integer quis. Tincidunt dui ut ornare lectus sit amet est placerat in Aliquam etiam erat velit scelerisque in dictum non consectetur a.Pharetra magna ac placerat vestibulum lectus mauris.Gravida arcu ac tortor dignissim convallis aenean.Placerat vestibulum lectus mauris ultrices eros in cursus turpis.Fames ac turpis egestas integer eget aliquet nibh praesent.Turpis cursus in hac habitasse platea dictumst quisque.Porttitor eget dolor morbi non arcu.Diam sollicitudin tempor id eu nisl.Quam nulla porttitor massa id.Cras sed felis eget velit.Suspendisse in est ante in nibh.Sapien faucibus et molestie ac feugiat sed lectus vestibulum.Sit amet cursus sit amet dictum sit amet justo donec.Purus sit amet luctus venenatis lectus magna fringilla urna porttitor.Dictum fusce ut placerat orci nulla.Felis eget nunc lobortis mattis.Lacus luctus accumsan tortor posuere.In nibh mauris cursus mattis.Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a.Aliquet risus feugiat in ante metus dictum.Sagittis nisl rhoncus mattis rhoncus urna.Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras.Nunc id cursus metus aliquam.Gravida cum sociis natoque penatibus et magnis dis parturient.Velit laoreet id donec ultrices tincidunt arcu non sodales neque.Malesuada fames ac turpis egestas sed tempus urna et.Porttitor leo a diam sollicitudin tempor id eu nisl nunc.Non sodales neque sodales ut.Morbi enim nunc faucibus a pellentesque sit.Hac habitasse platea dictumst vestibulum rhoncus est pellentesque.In est ante in nibh mauris cursus.", CreateDate = "2022-10-17 11:56:30", ViewsCount = 40, Score = 2.1, IsApproved = true, ImageUrl = "5.jpg" },
                    new Article() { ArticleId = 6, Title = "lectus proin nibh nisl condimentum", Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consequat mauris nunc congue nisi vitae. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Sed arcu non odio euismod lacinia at quis risus. Eget nunc lobortis mattis aliquam. In hac habitasse platea dictumst quisque sagittis. Turpis tincidunt id aliquet risus feugiat in ante metus. Varius vel pharetra vel turpis nunc eget. Quam vulputate dignissim suspendisse in est ante. Orci phasellus egestas tellus rutrum tellus. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Sapien eget mi proin sed libero enim sed. Aliquam eleifend mi in nulla. Tellus cras adipiscing enim eu turpis. Varius morbi enim nunc faucibus a pellentesque sit. Ipsum consequat nisl vel pretium lectus quam. Magnis dis parturient montes nascetur. Amet nisl suscipit adipiscing bibendum est ultricies integer quis. Tincidunt dui ut ornare lectus sit amet est placerat in Aliquam etiam erat velit scelerisque in dictum non consectetur a.Pharetra magna ac placerat vestibulum lectus mauris.Gravida arcu ac tortor dignissim convallis aenean.Placerat vestibulum lectus mauris ultrices eros in cursus turpis.Fames ac turpis egestas integer eget aliquet nibh praesent.Turpis cursus in hac habitasse platea dictumst quisque.Porttitor eget dolor morbi non arcu.Diam sollicitudin tempor id eu nisl.Quam nulla porttitor massa id.Cras sed felis eget velit.Suspendisse in est ante in nibh.Sapien faucibus et molestie ac feugiat sed lectus vestibulum.Sit amet cursus sit amet dictum sit amet justo donec.Purus sit amet luctus venenatis lectus magna fringilla urna porttitor.Dictum fusce ut placerat orci nulla.Felis eget nunc lobortis mattis.Lacus luctus accumsan tortor posuere.In nibh mauris cursus mattis.Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a.Aliquet risus feugiat in ante metus dictum.Sagittis nisl rhoncus mattis rhoncus urna.Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras.Nunc id cursus metus aliquam.Gravida cum sociis natoque penatibus et magnis dis parturient.Velit laoreet id donec ultrices tincidunt arcu non sodales neque.Malesuada fames ac turpis egestas sed tempus urna et.Porttitor leo a diam sollicitudin tempor id eu nisl nunc.Non sodales neque sodales ut.Morbi enim nunc faucibus a pellentesque sit.Hac habitasse platea dictumst vestibulum rhoncus est pellentesque.In est ante in nibh mauris cursus.", CreateDate = "2022-10-17 11:56:30", ViewsCount = 85, Score = 2.1, IsApproved = true, ImageUrl = "6.jpg" },
                    new Article() { ArticleId = 7, Title = "lectus proin nibh nisl condimentum", Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consequat mauris nunc congue nisi vitae. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Sed arcu non odio euismod lacinia at quis risus. Eget nunc lobortis mattis aliquam. In hac habitasse platea dictumst quisque sagittis. Turpis tincidunt id aliquet risus feugiat in ante metus. Varius vel pharetra vel turpis nunc eget. Quam vulputate dignissim suspendisse in est ante. Orci phasellus egestas tellus rutrum tellus. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Sapien eget mi proin sed libero enim sed. Aliquam eleifend mi in nulla. Tellus cras adipiscing enim eu turpis. Varius morbi enim nunc faucibus a pellentesque sit. Ipsum consequat nisl vel pretium lectus quam. Magnis dis parturient montes nascetur. Amet nisl suscipit adipiscing bibendum est ultricies integer quis. Tincidunt dui ut ornare lectus sit amet est placerat in Aliquam etiam erat velit scelerisque in dictum non consectetur a.Pharetra magna ac placerat vestibulum lectus mauris.Gravida arcu ac tortor dignissim convallis aenean.Placerat vestibulum lectus mauris ultrices eros in cursus turpis.Fames ac turpis egestas integer eget aliquet nibh praesent.Turpis cursus in hac habitasse platea dictumst quisque.Porttitor eget dolor morbi non arcu.Diam sollicitudin tempor id eu nisl.Quam nulla porttitor massa id.Cras sed felis eget velit.Suspendisse in est ante in nibh.Sapien faucibus et molestie ac feugiat sed lectus vestibulum.Sit amet cursus sit amet dictum sit amet justo donec.Purus sit amet luctus venenatis lectus magna fringilla urna porttitor.Dictum fusce ut placerat orci nulla.Felis eget nunc lobortis mattis.Lacus luctus accumsan tortor posuere.In nibh mauris cursus mattis.Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a.Aliquet risus feugiat in ante metus dictum.Sagittis nisl rhoncus mattis rhoncus urna.Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras.Nunc id cursus metus aliquam.Gravida cum sociis natoque penatibus et magnis dis parturient.Velit laoreet id donec ultrices tincidunt arcu non sodales neque.Malesuada fames ac turpis egestas sed tempus urna et.Porttitor leo a diam sollicitudin tempor id eu nisl nunc.Non sodales neque sodales ut.Morbi enim nunc faucibus a pellentesque sit.Hac habitasse platea dictumst vestibulum rhoncus est pellentesque.In est ante in nibh mauris cursus.", CreateDate = "2022-10-17 11:56:30", ViewsCount = 19, Score = 2.1, IsApproved = true, ImageUrl = "7.jpg"},
                    new Article() { ArticleId = 8, Title = "lectus proin nibh nisl condimentum", Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consequat mauris nunc congue nisi vitae. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Sed arcu non odio euismod lacinia at quis risus. Eget nunc lobortis mattis aliquam. In hac habitasse platea dictumst quisque sagittis. Turpis tincidunt id aliquet risus feugiat in ante metus. Varius vel pharetra vel turpis nunc eget. Quam vulputate dignissim suspendisse in est ante. Orci phasellus egestas tellus rutrum tellus. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Sapien eget mi proin sed libero enim sed. Aliquam eleifend mi in nulla. Tellus cras adipiscing enim eu turpis. Varius morbi enim nunc faucibus a pellentesque sit. Ipsum consequat nisl vel pretium lectus quam. Magnis dis parturient montes nascetur. Amet nisl suscipit adipiscing bibendum est ultricies integer quis. Tincidunt dui ut ornare lectus sit amet est placerat in Aliquam etiam erat velit scelerisque in dictum non consectetur a.Pharetra magna ac placerat vestibulum lectus mauris.Gravida arcu ac tortor dignissim convallis aenean.Placerat vestibulum lectus mauris ultrices eros in cursus turpis.Fames ac turpis egestas integer eget aliquet nibh praesent.Turpis cursus in hac habitasse platea dictumst quisque.Porttitor eget dolor morbi non arcu.Diam sollicitudin tempor id eu nisl.Quam nulla porttitor massa id.Cras sed felis eget velit.Suspendisse in est ante in nibh.Sapien faucibus et molestie ac feugiat sed lectus vestibulum.Sit amet cursus sit amet dictum sit amet justo donec.Purus sit amet luctus venenatis lectus magna fringilla urna porttitor.Dictum fusce ut placerat orci nulla.Felis eget nunc lobortis mattis.Lacus luctus accumsan tortor posuere.In nibh mauris cursus mattis.Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a.Aliquet risus feugiat in ante metus dictum.Sagittis nisl rhoncus mattis rhoncus urna.Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras.Nunc id cursus metus aliquam.Gravida cum sociis natoque penatibus et magnis dis parturient.Velit laoreet id donec ultrices tincidunt arcu non sodales neque.Malesuada fames ac turpis egestas sed tempus urna et.Porttitor leo a diam sollicitudin tempor id eu nisl nunc.Non sodales neque sodales ut.Morbi enim nunc faucibus a pellentesque sit.Hac habitasse platea dictumst vestibulum rhoncus est pellentesque.In est ante in nibh mauris cursus.", CreateDate = "2022-10-17 11:56:30", ViewsCount = 25, Score = 2.1, IsApproved = true, ImageUrl = "8.jpg"},
                    new Article() { ArticleId = 9, Title = "lectus proin nibh nisl condimentum", Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consequat mauris nunc congue nisi vitae. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Sed arcu non odio euismod lacinia at quis risus. Eget nunc lobortis mattis aliquam. In hac habitasse platea dictumst quisque sagittis. Turpis tincidunt id aliquet risus feugiat in ante metus. Varius vel pharetra vel turpis nunc eget. Quam vulputate dignissim suspendisse in est ante. Orci phasellus egestas tellus rutrum tellus. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Sapien eget mi proin sed libero enim sed. Aliquam eleifend mi in nulla. Tellus cras adipiscing enim eu turpis. Varius morbi enim nunc faucibus a pellentesque sit. Ipsum consequat nisl vel pretium lectus quam. Magnis dis parturient montes nascetur. Amet nisl suscipit adipiscing bibendum est ultricies integer quis. Tincidunt dui ut ornare lectus sit amet est placerat in Aliquam etiam erat velit scelerisque in dictum non consectetur a.Pharetra magna ac placerat vestibulum lectus mauris.Gravida arcu ac tortor dignissim convallis aenean.Placerat vestibulum lectus mauris ultrices eros in cursus turpis.Fames ac turpis egestas integer eget aliquet nibh praesent.Turpis cursus in hac habitasse platea dictumst quisque.Porttitor eget dolor morbi non arcu.Diam sollicitudin tempor id eu nisl.Quam nulla porttitor massa id.Cras sed felis eget velit.Suspendisse in est ante in nibh.Sapien faucibus et molestie ac feugiat sed lectus vestibulum.Sit amet cursus sit amet dictum sit amet justo donec.Purus sit amet luctus venenatis lectus magna fringilla urna porttitor.Dictum fusce ut placerat orci nulla.Felis eget nunc lobortis mattis.Lacus luctus accumsan tortor posuere.In nibh mauris cursus mattis.Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a.Aliquet risus feugiat in ante metus dictum.Sagittis nisl rhoncus mattis rhoncus urna.Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras.Nunc id cursus metus aliquam.Gravida cum sociis natoque penatibus et magnis dis parturient.Velit laoreet id donec ultrices tincidunt arcu non sodales neque.Malesuada fames ac turpis egestas sed tempus urna et.Porttitor leo a diam sollicitudin tempor id eu nisl nunc.Non sodales neque sodales ut.Morbi enim nunc faucibus a pellentesque sit.Hac habitasse platea dictumst vestibulum rhoncus est pellentesque.In est ante in nibh mauris cursus.", CreateDate = "2022-10-17 11:56:30", ViewsCount = 55, Score = 2.1, IsApproved = true, ImageUrl = "9.jpg"},
                    new Article() { ArticleId = 10, Title = "lectus proin nibh nisl condimentum", Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consequat mauris nunc congue nisi vitae. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Sed arcu non odio euismod lacinia at quis risus. Eget nunc lobortis mattis aliquam. In hac habitasse platea dictumst quisque sagittis. Turpis tincidunt id aliquet risus feugiat in ante metus. Varius vel pharetra vel turpis nunc eget. Quam vulputate dignissim suspendisse in est ante. Orci phasellus egestas tellus rutrum tellus. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Sapien eget mi proin sed libero enim sed. Aliquam eleifend mi in nulla. Tellus cras adipiscing enim eu turpis. Varius morbi enim nunc faucibus a pellentesque sit. Ipsum consequat nisl vel pretium lectus quam. Magnis dis parturient montes nascetur. Amet nisl suscipit adipiscing bibendum est ultricies integer quis. Tincidunt dui ut ornare lectus sit amet est placerat in Aliquam etiam erat velit scelerisque in dictum non consectetur a.Pharetra magna ac placerat vestibulum lectus mauris.Gravida arcu ac tortor dignissim convallis aenean.Placerat vestibulum lectus mauris ultrices eros in cursus turpis.Fames ac turpis egestas integer eget aliquet nibh praesent.Turpis cursus in hac habitasse platea dictumst quisque.Porttitor eget dolor morbi non arcu.Diam sollicitudin tempor id eu nisl.Quam nulla porttitor massa id.Cras sed felis eget velit.Suspendisse in est ante in nibh.Sapien faucibus et molestie ac feugiat sed lectus vestibulum.Sit amet cursus sit amet dictum sit amet justo donec.Purus sit amet luctus venenatis lectus magna fringilla urna porttitor.Dictum fusce ut placerat orci nulla.Felis eget nunc lobortis mattis.Lacus luctus accumsan tortor posuere.In nibh mauris cursus mattis.Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a.Aliquet risus feugiat in ante metus dictum.Sagittis nisl rhoncus mattis rhoncus urna.Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras.Nunc id cursus metus aliquam.Gravida cum sociis natoque penatibus et magnis dis parturient.Velit laoreet id donec ultrices tincidunt arcu non sodales neque.Malesuada fames ac turpis egestas sed tempus urna et.Porttitor leo a diam sollicitudin tempor id eu nisl nunc.Non sodales neque sodales ut.Morbi enim nunc faucibus a pellentesque sit.Hac habitasse platea dictumst vestibulum rhoncus est pellentesque.In est ante in nibh mauris cursus.", CreateDate = "2022-10-17 11:56:30", ViewsCount = 8, Score = 2.1, IsApproved = true, ImageUrl = "10.jpg"},
                    new Article() { ArticleId = 11, Title = "lectus proin nibh nisl condimentum", Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consequat mauris nunc congue nisi vitae. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Sed arcu non odio euismod lacinia at quis risus. Eget nunc lobortis mattis aliquam. In hac habitasse platea dictumst quisque sagittis. Turpis tincidunt id aliquet risus feugiat in ante metus. Varius vel pharetra vel turpis nunc eget. Quam vulputate dignissim suspendisse in est ante. Orci phasellus egestas tellus rutrum tellus. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Sapien eget mi proin sed libero enim sed. Aliquam eleifend mi in nulla. Tellus cras adipiscing enim eu turpis. Varius morbi enim nunc faucibus a pellentesque sit. Ipsum consequat nisl vel pretium lectus quam. Magnis dis parturient montes nascetur. Amet nisl suscipit adipiscing bibendum est ultricies integer quis. Tincidunt dui ut ornare lectus sit amet est placerat in Aliquam etiam erat velit scelerisque in dictum non consectetur a.Pharetra magna ac placerat vestibulum lectus mauris.Gravida arcu ac tortor dignissim convallis aenean.Placerat vestibulum lectus mauris ultrices eros in cursus turpis.Fames ac turpis egestas integer eget aliquet nibh praesent.Turpis cursus in hac habitasse platea dictumst quisque.Porttitor eget dolor morbi non arcu.Diam sollicitudin tempor id eu nisl.Quam nulla porttitor massa id.Cras sed felis eget velit.Suspendisse in est ante in nibh.Sapien faucibus et molestie ac feugiat sed lectus vestibulum.Sit amet cursus sit amet dictum sit amet justo donec.Purus sit amet luctus venenatis lectus magna fringilla urna porttitor.Dictum fusce ut placerat orci nulla.Felis eget nunc lobortis mattis.Lacus luctus accumsan tortor posuere.In nibh mauris cursus mattis.Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a.Aliquet risus feugiat in ante metus dictum.Sagittis nisl rhoncus mattis rhoncus urna.Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras.Nunc id cursus metus aliquam.Gravida cum sociis natoque penatibus et magnis dis parturient.Velit laoreet id donec ultrices tincidunt arcu non sodales neque.Malesuada fames ac turpis egestas sed tempus urna et.Porttitor leo a diam sollicitudin tempor id eu nisl nunc.Non sodales neque sodales ut.Morbi enim nunc faucibus a pellentesque sit.Hac habitasse platea dictumst vestibulum rhoncus est pellentesque.In est ante in nibh mauris cursus.", CreateDate = "2022-10-17 11:56:30", ViewsCount = 7, Score = 2.1, IsApproved = true, ImageUrl = "11.jpg"},
                    new Article() { ArticleId = 12, Title = "lectus proin nibh nisl condimentum", Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consequat mauris nunc congue nisi vitae. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Sed arcu non odio euismod lacinia at quis risus. Eget nunc lobortis mattis aliquam. In hac habitasse platea dictumst quisque sagittis. Turpis tincidunt id aliquet risus feugiat in ante metus. Varius vel pharetra vel turpis nunc eget. Quam vulputate dignissim suspendisse in est ante. Orci phasellus egestas tellus rutrum tellus. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Sapien eget mi proin sed libero enim sed. Aliquam eleifend mi in nulla. Tellus cras adipiscing enim eu turpis. Varius morbi enim nunc faucibus a pellentesque sit. Ipsum consequat nisl vel pretium lectus quam. Magnis dis parturient montes nascetur. Amet nisl suscipit adipiscing bibendum est ultricies integer quis. Tincidunt dui ut ornare lectus sit amet est placerat in Aliquam etiam erat velit scelerisque in dictum non consectetur a.Pharetra magna ac placerat vestibulum lectus mauris.Gravida arcu ac tortor dignissim convallis aenean.Placerat vestibulum lectus mauris ultrices eros in cursus turpis.Fames ac turpis egestas integer eget aliquet nibh praesent.Turpis cursus in hac habitasse platea dictumst quisque.Porttitor eget dolor morbi non arcu.Diam sollicitudin tempor id eu nisl.Quam nulla porttitor massa id.Cras sed felis eget velit.Suspendisse in est ante in nibh.Sapien faucibus et molestie ac feugiat sed lectus vestibulum.Sit amet cursus sit amet dictum sit amet justo donec.Purus sit amet luctus venenatis lectus magna fringilla urna porttitor.Dictum fusce ut placerat orci nulla.Felis eget nunc lobortis mattis.Lacus luctus accumsan tortor posuere.In nibh mauris cursus mattis.Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a.Aliquet risus feugiat in ante metus dictum.Sagittis nisl rhoncus mattis rhoncus urna.Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras.Nunc id cursus metus aliquam.Gravida cum sociis natoque penatibus et magnis dis parturient.Velit laoreet id donec ultrices tincidunt arcu non sodales neque.Malesuada fames ac turpis egestas sed tempus urna et.Porttitor leo a diam sollicitudin tempor id eu nisl nunc.Non sodales neque sodales ut.Morbi enim nunc faucibus a pellentesque sit.Hac habitasse platea dictumst vestibulum rhoncus est pellentesque.In est ante in nibh mauris cursus.", CreateDate = "2022-10-17 11:56:30", ViewsCount = 5, Score = 2.1, IsApproved = true, ImageUrl = "12.jpg" }
                );
            modelBuilder
                .Entity<Category>()
                .HasData(
                    new Category() {CategoryId=1, CategoryName="Teknoloji" },
                    new Category() {CategoryId=2, CategoryName="Seyahat" },
                    new Category() {CategoryId=3, CategoryName="Sanat ve Fotografcilik" },
                    new Category() {CategoryId=4, CategoryName="Yemek" },
                    new Category() {CategoryId=5, CategoryName="Saglik ve Fitness" },
                    new Category() {CategoryId=6, CategoryName="Moda" },
                    new Category() {CategoryId=7, CategoryName="Finans" }
                );
            modelBuilder
                .Entity<ArticleCategory>()
                .HasData(
                    new ArticleCategory() {ArticleId=1, CategoryId=1 },
                    new ArticleCategory() {ArticleId=1, CategoryId=2 },
                    new ArticleCategory() {ArticleId=1, CategoryId=3 },

                    new ArticleCategory() {ArticleId=2, CategoryId=1 },
                    new ArticleCategory() {ArticleId=2, CategoryId=2 },
                    new ArticleCategory() {ArticleId=2, CategoryId=3 },

                    new ArticleCategory() {ArticleId=3, CategoryId=1 },
                    new ArticleCategory() {ArticleId=3, CategoryId=2 },

                    new ArticleCategory() {ArticleId=4, CategoryId=3 },
                    new ArticleCategory() {ArticleId=4, CategoryId=4 },

                    new ArticleCategory() {ArticleId=5, CategoryId=4 },
                    new ArticleCategory() {ArticleId=5, CategoryId=5 },

                    new ArticleCategory() {ArticleId=6, CategoryId=6 },
                    new ArticleCategory() {ArticleId=6, CategoryId=7 },

                    new ArticleCategory() {ArticleId=7, CategoryId=1 },
                    new ArticleCategory() {ArticleId=7, CategoryId=2 },

                    new ArticleCategory() {ArticleId=8, CategoryId=1 },

                    new ArticleCategory() {ArticleId=9, CategoryId=2 },
                    new ArticleCategory() {ArticleId=9, CategoryId=1 },

                    new ArticleCategory() {ArticleId=10, CategoryId=2 },

                    new ArticleCategory() {ArticleId=11, CategoryId=1 },
                    new ArticleCategory() {ArticleId=11, CategoryId=2 },

                    new ArticleCategory() {ArticleId=12, CategoryId=1 }
                );
            
            modelBuilder
                .Entity<Comment>()
                .HasData(
                    new Comment() {CommentId=1, Name= "ahmet", Text= "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aenean vel elit scelerisque mauris pellentesque. Consectetur a erat nam at lectus urna duis convallis.", CommentDate= "2022-10-17 12:56:30", ArticleId=1 },
                    new Comment() {CommentId=2, Name= "alii", Text= "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aenean vel elit scelerisque mauris pellentesque. Consectetur a erat nam at lectus urna duis convallis.", CommentDate= "2022-10-17 12:56:30", ArticleId=1 },
                    new Comment() {CommentId=3, Name= "yasar1", Text= "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aenean vel elit scelerisque mauris pellentesque. Consectetur a erat nam at lectus urna duis convallis.", CommentDate= "2022-10-17 12:56:30", ArticleId=1 },
                    new Comment() {CommentId=4, Name= "ahmet", Text= "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aenean vel elit scelerisque mauris pellentesque. Consectetur a erat nam at lectus urna duis convallis.", CommentDate= "2022-10-17 12:56:30", ArticleId=2 },
                    new Comment() {CommentId=5, Name= "sila5", Text= "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aenean vel elit scelerisque mauris pellentesque. Consectetur a erat nam at lectus urna duis convallis.", CommentDate= "2022-10-17 12:56:30", ArticleId=2 },
                    new Comment() {CommentId=6, Name= "yasar1", Text= "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aenean vel elit scelerisque mauris pellentesque. Consectetur a erat nam at lectus urna duis convallis.", CommentDate= "2022-10-17 12:56:30", ArticleId=3 },
                    new Comment() {CommentId=7, Name= "ahmet", Text= "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aenean vel elit scelerisque mauris pellentesque. Consectetur a erat nam at lectus urna duis convallis.", CommentDate= "2022-10-17 12:56:30", ArticleId=3 },
                    new Comment() {CommentId=8, Name= "alii", Text= "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aenean vel elit scelerisque mauris pellentesque. Consectetur a erat nam at lectus urna duis convallis.", CommentDate= "2022-10-17 12:56:30", ArticleId=3 },
                    new Comment() {CommentId=9, Name= "sila5", Text= "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aenean vel elit scelerisque mauris pellentesque. Consectetur a erat nam at lectus urna duis convallis.", CommentDate= "2022-10-17 12:56:30", ArticleId=2 },
                    new Comment() {CommentId=10, Name= "alii", Text= "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aenean vel elit scelerisque mauris pellentesque. Consectetur a erat nam at lectus urna duis convallis.", CommentDate= "2022-10-17 12:56:30", ArticleId=1 }
                );

        }
    }
}